# This CircleCI config uses a workflow to test on 2 versions of python and upload releases to PyPI
#
# The test-and-release workflow runs the following jobs:
# 1. test-3.6 - test tags and branches under Python 3.6
# 2. release - after both test jobs succeed, upload to PyPi for tags (but not for branches).
#
# Note that the test jobs have a tags filter. This is because the release job
# (which depends on the test jobs and needs a tag filter) wouldn't run unless its dependencies
# also had tag filters (even if they didn't exclude anything)

version: 2
workflows:
  version: 2
  test-and-release:
    jobs:
      - test-3.6:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - test-3.6
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "devRequirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r devRequirements.txt
      - save_cache:
          key: deps-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "devRequirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            source venv/bin/activate
            ./runtests.sh
  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r devRequirements.txt
            pip install twine
            python setup.py bdist_wheel --universal
            twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*
