version: 2
workflows:
  version: 2
  test-and-release:
    jobs:
      - test-3.6:
          filters:
            tags:
              only: /.*/
      - test-2.7:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - test-3.6
            - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "devRequirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r devRequirements.txt
      - save_cache:
          key: deps-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "devRequirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            source venv/bin/activate
            ./runtests.sh
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r devRequirements.txt
            pip install twine
            python setup.py bdist_wheel --universal
            twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*
